/*
 * Tramvajske stanice
 *
 * API napravljen u sklopu 3. laboratorijske vježbe za predmet Otvoreno Računalstvo. Definira operacije koje nude mogućnosti manipuliranja skupa podataka o tramvajskim stanicama.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
	"context"
	"github.com/jackc/pgx/v5"
	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "test/api/go"
)


func main() {
	log.Printf("Server started")

	connStr := "host=localhost port=5432 dbname=otvorenoRacunalstvo user=postgres password=1234"
	
	conn, err := pgx.Connect(context.Background(), connStr)
	if err != nil {
		log.Fatalf("Unable to connect to database: %v", err)
	}
	defer conn.Close(context.Background())

	router := sw.NewRouter(conn)

	log.Fatal(http.ListenAndServe(":8080", router))
}
